# DeepSeek 1_4B, 0_4A Model
defaults:
  - _self_
  - train: train_deepseek_v3_1_4b.yaml

experiment:
  exp_name: OpenSeek-Small-v1-Baseline
  dataset_base_dir: ../OpenSeek-Pretrain-100B
  seed: 42
  save_steps: 600
  load: null
  exp_dir: ${experiment.exp_name}
  ckpt_format: torch
  task:
    type: train
    backend: megatron
    entrypoint: flagscale/train/train_gpt.py
  runner:
    no_shared_fs: false
    backend: torchrun
    rdzv_backend: static
    ssh_port: 22
    nnodes: 1
    nproc_per_node: 1
    hostfile: null
  cmds:
    before_start: "ulimit -n 1048576 && source /root/miniconda3/bin/activate flagscale"
  envs:
    VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    DEVICE_MAX_CONNECTIONS: 1

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
