system:
  recompute_method: "uniform"
  recompute_granularity: "full"
  recompute_num_layers: 6
  moe_router_dtype: fp32
  no_shared_fs: ${experiment.runner.no_shared_fs}
  num_workers: 4
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  expert_model_parallel_size: 1
  context_parallel_size: 1
  disable_bias_linear: true
  reset_position_ids: True
  reset_attention_mask: True
  qk_layernorm: true
  sequence_parallel: true
  use_distributed_optimizer: true
  overlap_grad_reduce: true
  overlap_param_gather: true
  finetune: false
  precision:
    bf16: true
    attention_softmax_in_fp32: true
    accumulate_allreduce_grads_in_fp32: true
  logging:
    log_interval: 1
    tensorboard_log_interval: 1
    wandb_project: ${experiment.exp_name}
    wandb_exp_name: ${experiment.exp_name}
    log_timers_to_tensorboard: true
    log_validation_ppl_to_tensorboard: true
    log_throughput: true
    log_params_norm: true
    log_num_zeros_in_grad: true
    log_memory_to_tensorboard: true
  checkpoint:
    save_interval: ${experiment.save_steps}
    load: ${experiment.load}
    ckpt_format: ${experiment.ckpt_format}

model:
  transformer_impl: transformer_engine
  num_layers: 6
  hidden_size: 1280
  num_attention_heads: 10
  group_query_attention: false
  num_query_groups: 10
  seq_length: 4096
  max_position_embeddings: 4096
  norm_epsilon: 1e-6
  use_rotary_position_embeddings: true
  rotary_base: 1000000
  swiglu: true
  normalization: RMSNorm
  init_method_std: 6e-3
  attention_dropout: 0.0
  hidden_dropout: 0.0
  clip_grad: 1.0
  position_embedding_type: rope
  untie_embeddings_and_output_weights: false
  no_position_embedding: true
  no_rope_fusion: true

  # mla args
  multi_latent_attention: true
  kv_lora_rank: 512
  qk_head_dim: 128
  qk_pos_emb_head_dim: 64
  v_head_dim: 128

  # moe args
  ffn_hidden_size: 7168
  moe_ffn_hidden_size: 896
  moe_grouped_gemm: true
  moe_shared_expert_intermediate_size: 1792
  num_experts: 64
  moe_router_load_balancing_type: "seq_aux_loss"
  moe_router_score_function: sigmoid
  moe_router_enable_expert_bias: true
  moe_router_bias_update_rate: 0.001
  moe_aux_loss_coeff: 0.0001
  moe_layer_freq: "[0]+[1]*5"
  moe_router_num_groups: 1
  moe_router_group_topk: 1
  moe_router_topk: 6
  moe_router_topk_scaling_factor: 2.446
  moe_token_dispatcher_type: "alltoall"

  # training
  seed: ${experiment.seed}
  micro_batch_size: 1
  global_batch_size: 1024
  eval_iters: 0
  train_samples: 24576000 # 100B tokens

  optimizer:
    weight_decay: 0.1
    adam_beta1: 0.9
    adam_beta2: 0.95
    lr_scheduler:
      lr: 3.0e-3
      min_lr: 3.0e-4
      lr_warmup_samples: 2048000
      lr_decay_style: cosine

data:
  # PyEdu integration: Enhanced code training with educational Python dataset
  data_path:
    # Existing code datasets (reduced weights to make room for pyedu)
    - 0.8000  # Reduced from original weight
    - ${experiment.dataset_base_dir}/code-high/part_13_text_document
    - 0.9000  # Reduced from original weight
    - ${experiment.dataset_base_dir}/code-low/part_36_text_document
    - 0.8000  # Reduced from original weight
    - ${experiment.dataset_base_dir}/code-mid/part_37_text_document
    
    # PyEdu dataset integration - high-quality educational Python code
    - 1.2000  # Higher weight for high-quality educational content
    - ${experiment.dataset_base_dir}/pyedu/pyedu_text_document
    
    # Existing stack dataset (maintained)
    - 0.4229
    - ${experiment.dataset_base_dir}/stack/018_00000_text_document
    
    # CoT synthesis for code (enhanced with pyedu influence)
    - 0.5000  # Slightly increased for better code reasoning
    - ${experiment.dataset_base_dir}/cot_synthesis2_code-high/4_text_document
    - 0.7000  # Slightly increased
    - ${experiment.dataset_base_dir}/cot_synthesis2_code-low/6_text_document
    - 0.9000  # Slightly increased
    - ${experiment.dataset_base_dir}/cot_synthesis2_code-mid/23_text_document
    
    # Math datasets (maintained for balanced training)
    - 1.8165
    - ${experiment.dataset_base_dir}/math-high/part_04_text_document
    - 1.6940
    - ${experiment.dataset_base_dir}/math-low/part_10_text_document
    - 1.6311
    - ${experiment.dataset_base_dir}/math-mid/part_07_text_document
    
    # ArXiv for scientific content (maintained)
    - 0.6414
    - ${experiment.dataset_base_dir}/arxiv/007_00000_text_document
    
    # Wiki for general knowledge (maintained)
    - 0.4202
    - ${experiment.dataset_base_dir}/wiki/012_00000_text_document

  split: 1
  no_mmap_bin_files: true
  tokenizer:
    tokenizer_type: QwenTokenizerFS
    tokenizer_path: ../hf_openseek/tokenizer
    vocab_size: 151851
    make_vocab_size_divisible_by: 64